version: "3.8"
services:
  dev-env:
    build:
      context: .
    volumes:
      - ./workspaces:/workspace
    ports:
      - "8080:8080"
    tty: true
  fastapi:
    build: 
      context: ./TestSocket
      dockerfile: ../Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASEURL=postgresql://postgres:postgres@db/postgres
    networks:
      - backend
    command: uvicorn fast_api_test_server:app --host 0.0.0.0 --port 8000
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
networks:
  backend:
    driver: bridge

volumes:
  postgres_data: 