version: "3.8"
services:
  fastapi:
    build: 
      context: ./TestSocket
      dockerfile: ../Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASEURL=postgresql://postgres:postgres@db:5432/postgres
    networks:
      - backend
    volumes:
      - ./db:/workspace/db
    command: uvicorn fast_api_test_server:app --host 0.0.0.0 --port 8000
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_data: 